# permissions for end users to view mynginxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mynginx-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: simplest-operator
    app.kubernetes.io/part-of: simplest-operator
    app.kubernetes.io/managed-by: kustomize
  name: mynginx-viewer-role
rules:
- apiGroups:
  - example.io.example.io
  resources:
  - mynginxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.io.example.io
  resources:
  - mynginxes/status
  verbs:
  - get
